apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  annotations:
    tekton.dev/docker-0: https://quay.io # Replace with your registry URL
type: kubernetes.io/basic-auth
stringData:
  username: <your-registry-username>
  password: <your-registry-password>
