apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: <NAMESPACE>
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    services.loadbalancers: "0"
    services.nodeports: "0"
    persistentvolumeclaims: "5"
    requests.storage: 50Gi
    count/deployments.apps: "10"
    count/statefulsets.apps: "5"
