apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha-app
  namespace: mlflow-postgres
spec:
  instances: 3

  storage:
    size: 10Gi

  postgresql:
    parameters:
      shared_buffers: 256MB

  bootstrap:
    initdb:
      database: mlflow
      owner: mlflow

  enableSuperuserAccess: true

  affinity:
    enablePodAntiAffinity: true
