kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: fedora-golden-prefer
  namespace: openshift
  labels:
    app.kubernetes.io/part-of: hyperconverged-cluster
    template.kubevirt.io/architecture: amd64
    flavor.template.kubevirt.io/small: 'true'
    template.kubevirt.io/version: v0.32.2
    app.kubernetes.io/version: 4.18.0
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: fedora-golden
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    app.kubernetes.io/name: custom-templates
    vm.kubevirt.io/template.namespace: openshift
    os.template.kubevirt.io/fedora40: 'true'
    workload.template.kubevirt.io/server: 'true'
    os.template.kubevirt.io/fedora41: 'true'
  annotations:
    name.os.template.kubevirt.io/fedora41: Fedora Linux 40 or higher
    template.kubevirt.io/provider: ''
    template.kubevirt.io/provider-url: 'https://www.fedoraproject.org'
    template.kubevirt.io/containerdisks: |
      quay.io/containerdisks/fedora:latest
      quay.io/containerdisks/fedora:40
      quay.io/containerdisks/fedora:41
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: Fedora-golden-perfer
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    template.kubevirt.io/images: |
      https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
      https://download.fedoraproject.org/pub/fedora/linux/releases/41/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-41-1.4.qcow2
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.openshift.io/bindable: 'false'
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: 'true'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    tags: 'hidden,kubevirt,virtualmachine,fedora'
    template.kubevirt.io/provider-support-level: Community
    description: Template for Fedora Linux 40 VM or newer. A PVC with the Fedora disk image must be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-x
    name.os.template.kubevirt.io/fedora40: Fedora Linux 40 or higher
    openshift.io/provider-display-name: ''
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: template.openshift.io/v1
      time: '2025-08-18T07:33:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:template.kubevirt.io/editable': {}
            'f:operator-sdk/primary-resource': {}
            'f:operator-sdk/primary-resource-type': {}
            'f:defaults.template.kubevirt.io/disk': {}
            'f:template.kubevirt.io/provider-support-level': {}
            'f:description': {}
            'f:template.openshift.io/bindable': {}
            'f:iconClass': {}
            'f:name.os.template.kubevirt.io/fedora40': {}
            'f:openshift.kubevirt.io/pronounceable-suffix-for-name-expression': {}
            'f:name.os.template.kubevirt.io/fedora41': {}
            'f:tags': {}
            .: {}
            'f:template.kubevirt.io/provider': {}
            'f:template.kubevirt.io/provider-url': {}
            'f:template.kubevirt.io/containerdisks': {}
            'f:openshift.io/support-url': {}
            'f:openshift.io/provider-display-name': {}
            'f:template.kubevirt.io/images': {}
            'f:openshift.io/display-name': {}
            'f:template.kubevirt.io/version': {}
            'f:openshift.io/documentation-url': {}
          'f:labels':
            'f:vm.kubevirt.io/template.namespace': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:app.kubernetes.io/part-of': {}
            'f:os.template.kubevirt.io/fedora40': {}
            'f:template.kubevirt.io/architecture': {}
            'f:os.template.kubevirt.io/fedora41': {}
            'f:workload.template.kubevirt.io/server': {}
            'f:flavor.template.kubevirt.io/small': {}
            'f:app.kubernetes.io/version': {}
            'f:template.kubevirt.io/type': {}
            'f:vm.kubevirt.io/template': {}
            'f:template.kubevirt.io/version': {}
            'f:app.kubernetes.io/component': {}
        'f:objects': {}
        'f:parameters': {}
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.memory.guest",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 2147483648
            }
          ]
      labels:
        app: '${NAME}'
        kubevirt.io/dynamic-credentials-support: 'true'
        vm.kubevirt.io/template: fedora-golden-prefer
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.namespace: swongpai-virt-import
      name: '${NAME}'
      namespace: openshift-virtualization-os-images
    spec:
      dataVolumeTemplates:
        - metadata:
            name: '${NAME}-rootdisk'
          spec:
            source:
              pvc:
                name: fedora-golden
                namespace: openshift-virtualization-os-images
            storage:
              resources:
                requests:
                  storage: 30Gi
              storageClassName: ocs-external-storagecluster-ceph-rbd
      runStrategy: Halted
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: small
            vm.kubevirt.io/os: fedora
            vm.kubevirt.io/workload: server
          labels:
            project: demo-ocp
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: small
        spec:
          architecture: amd64
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: cloudinitdisk
                  bootOrder: 2
                - disk:
                    bus: virtio
                  name: rootdisk
                  bootOrder: 1
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              rng: {}
            features:
              smm:
                enabled: true
            firmware:
              bootloader:
                efi: {}
            memory:
              guest: 2Gi
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - dataVolume:
                name: '${NAME}-rootdisk'
              name: rootdisk
            - cloudInitNoCloud:
                userData: |
                  #cloud-config
                  user: fedora
                  password: fedora
                  chpasswd:
                    expire: false
              name: cloudinitdisk
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: project
                          operator: In
                          values:
                            - demo-ocp
                    topologyKey: kubernetes.io/hostname
                  weight: 100
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'fedora-[a-z0-9]{16}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: fedora
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images
  - name: CLOUD_USER_PASSWORD
    description: Randomized password for the cloud-init user fedora
    generate: expression
    from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
