apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Surote/ocp-configuration.git
    targetRevision: main
    path: config
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
