apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-maas-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Surote/ocp-configuration.git
    targetRevision: main
    path: config/openshift-ai-maas-config
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
